title: Charith Reddy Gopavaram # your name (or website title) here
logo: <img src="https://github.com/CharithReddyG/CharithReddyG.github.io/blob/7aaee5f4336f4a15ddf070228386ea681fbb48fe/1711652910391.jpeg?raw=true" alt="Profile Logo" style="border-radius: 50%; width: 200px; height: 200px;">

[LinkedIn](https://www.linkedin.com/in/charith-reddy-gopavaram-245916171) | [GitHub](https://github.com/CharithReddyG)

description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing a Master's in Business Analysis (MSBA) at David Eccles School of Business,  University of Utah
  <br><br>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
